# =========================
# Core: nhẹ, ít task, ít overhead
# =========================
spark.master                        spark://spark-master:7077
spark.sql.shuffle.partitions         4
spark.default.parallelism            4
spark.sql.adaptive.enabled           true

# =========================
# Memory: hạn chế phình + giảm cache
# =========================
spark.memory.fraction                0.4
spark.memory.storageFraction         0.2
spark.sql.inMemoryColumnarStorage.batchSize  10000

# =========================
# Local dirs & work
# =========================
spark.local.dir                      /opt/spark/work
spark.worker.cleanup.enabled         true
spark.worker.cleanup.interval        600
spark.worker.cleanup.appDataTtl      3600

# =========================
# Ivy cache: tránh bơm vào home mặc định
# =========================
spark.jars.ivy                       /opt/ivy-cache

# =========================
# S3A / MinIO defaults (đỡ phải gõ)
# =========================
spark.hadoop.fs.s3a.endpoint                 http://minio:9000
spark.hadoop.fs.s3a.path.style.access        true
spark.hadoop.fs.s3a.connection.ssl.enabled   false
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.access.key               minio
spark.hadoop.fs.s3a.secret.key               minio123
